// Generated by Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@protocol BasicViewDelegate;
@class BasicViewConfiguration;
@class Coordinates;
@class ReactionResultRecord;
@class NSCoder;
@class UIImage;

SWIFT_CLASS("_TtC10MorphiiSDK9BasicView")
@interface BasicView : UIView
@property (nonatomic, strong) id <BasicViewDelegate> _Nullable delegate;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(BasicViewConfiguration * _Nonnull)configuration delegate:(id <BasicViewDelegate> _Nullable)delegate OBJC_DESIGNATED_INITIALIZER;
- (void)submitWithCoord:(Coordinates * _Nonnull)coord completion:(void (^ _Nonnull)(NSArray<ReactionResultRecord *> * _Nonnull))completion;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)submitWithCompletion:(void (^ _Nonnull)(NSArray<ReactionResultRecord *> * _Nonnull))completion;
- (void)resetWithComment:(BOOL)comment;
- (UIImage * _Nullable)pngWithSize:(CGSize)size;
- (void)didMoveToSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class MorphiiObject;
@class CommentObject;

SWIFT_CLASS("_TtCC10MorphiiSDK9BasicView15BasicViewObject")
@interface BasicViewObject : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified id;
@property (nonatomic, strong) MorphiiObject * _Nullable morphii;
@property (nonatomic, strong) CommentObject * _Nullable comment;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtCC10MorphiiSDK9BasicView13MorphiiObject")
@interface MorphiiObject : NSObject
@property (nonatomic) BOOL selected;
@property (nonatomic) NSInteger weight;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtCC10MorphiiSDK9BasicView13CommentObject")
@interface CommentObject : NSObject
@property (nonatomic) BOOL required;
@property (nonatomic) NSInteger length;
@property (nonatomic, copy) NSString * _Nullable value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class MorphiiConfiguration;
@class Target;
@class Project;
@class Comment;
@class Options;
@class User;

SWIFT_CLASS("_TtC10MorphiiSDK22BasicViewConfiguration")
@interface BasicViewConfiguration : NSObject
- (nonnull instancetype)initWithMorphiiConfig:(MorphiiConfiguration * _Nonnull)morphiiConfig target:(Target * _Nonnull)target project:(Project * _Nonnull)project comment:(Comment * _Nonnull)comment options:(Options * _Nonnull)options user:(User * _Nullable)user OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP10MorphiiSDK17BasicViewDelegate_")
@protocol BasicViewDelegate
- (void)commentChangeWithType:(NSString * _Nonnull)type commentRequiredValid:(BOOL)commentRequiredValid view:(BasicViewObject * _Nonnull)view;
@end


SWIFT_CLASS("_TtC10MorphiiSDK7Comment")
@interface Comment : NSObject
- (nonnull instancetype)initWithShow:(BOOL)show required:(BOOL)required maxLength:(NSInteger)maxLength label:(NSString * _Nonnull)label hintText:(NSString * _Nonnull)hintText OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10MorphiiSDK20MorphiiConfiguration")
@interface MorphiiConfiguration : NSObject
@property (nonatomic, readonly) BOOL showName;
- (nonnull instancetype)initWithShowName:(BOOL)showName OBJC_DESIGNATED_INITIALIZER;
- (void)addWithId:(NSString * _Nonnull)id name:(NSString * _Nullable)name weight:(NSInteger)weight;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10MorphiiSDK10MorphiiSDK")
@interface MorphiiSDK : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC10MorphiiSDK10MorphiiSDK11Coordinates")
@interface Coordinates : NSObject
- (nonnull instancetype)initWithLat:(double)lat lng:(double)lng OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtCC10MorphiiSDK10MorphiiSDK7Morphii")
@interface Morphii : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified id;
@property (nonatomic, copy) NSString * _Null_unspecified name;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name weight:(NSInteger)weight OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtCC10MorphiiSDK10MorphiiSDK11MorphiiList")
@interface MorphiiList : NSObject
@property (nonatomic, copy) NSArray<Morphii *> * _Nonnull ids;
- (nonnull instancetype)initWithShowName:(BOOL)showName OBJC_DESIGNATED_INITIALIZER;
- (void)addWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name weight:(NSInteger)weight;
- (NSArray<NSString *> * _Nonnull)getIDs;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtCC10MorphiiSDK10MorphiiSDK14ReactionResult")
@interface ReactionResult : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified viewId;
@property (nonatomic, copy) NSString * _Null_unspecified reactionId;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Null_unspecified reactionRecord;
- (nonnull instancetype)initWithIsSubmitted:(BOOL)isSubmitted viewId:(NSString * _Nonnull)viewId reactionId:(NSString * _Nonnull)reactionId reactionRecord:(NSDictionary<NSString *, NSString *> * _Nonnull)reactionRecord OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class ReactionError;

SWIFT_CLASS("_TtCC10MorphiiSDK10MorphiiSDK21AuthenticationResults")
@interface AuthenticationResults : NSObject
@property (nonatomic) BOOL isAuthenticated;
@property (nonatomic, strong) ReactionError * _Nullable error;
- (nonnull instancetype)initWithIsAuthenticated:(BOOL)isAuthenticated jwt:(NSString * _Nullable)jwt apiKey:(NSString * _Nullable)apiKey sessionId:(NSString * _Nullable)sessionId error:(ReactionError * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10MorphiiSDK20MorphiiSelectionView")
@interface MorphiiSelectionView : UIView
- (void)didMoveToSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP10MorphiiSDK28MorphiiSelectionViewDelegate_")
@protocol MorphiiSelectionViewDelegate
- (void)selectedMorphiiWithMorphiiConfiguration:(MorphiiConfiguration * _Nonnull)morphiiConfiguration;
@end


SWIFT_CLASS("_TtC10MorphiiSDK14MorphiiService")
@interface MorphiiService : NSObject
@property (nonatomic, strong) Project * _Null_unspecified project;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL production;)
+ (BOOL)production;
+ (void)setProduction:(BOOL)value;
+ (MorphiiService * _Nonnull)sharedInstance;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (void)authenticateWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password accountId:(NSString * _Nonnull)accountId completion:(void (^ _Nonnull)(AuthenticationResults * _Nonnull))completion;
- (BasicView * _Nonnull)addWithContainerView:(UIView * _Nonnull)containerView config:(BasicViewConfiguration * _Nonnull)config delegate:(id <BasicViewDelegate> _Nullable)delegate;
- (MorphiiSelectionView * _Nullable)addSelectionViewWithInitialIntensity:(double)initialIntensity config:(MorphiiConfiguration * _Nonnull)config delegate:(id <MorphiiSelectionViewDelegate> _Nonnull)delegate;
- (void)submitWithCompletion:(void (^ _Nonnull)(NSArray<ReactionResultRecord *> * _Nonnull))completion;
- (void)removeWithBasicView:(BasicView * _Nonnull)basicView;
- (void)resetWithComment:(BOOL)comment;
@end


SWIFT_CLASS("_TtC10MorphiiSDK7Options")
@interface Options : NSObject
- (nonnull instancetype)initWithStage:(NSString * _Nonnull)stage initialIntensity:(double)initialIntensity OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10MorphiiSDK7Project")
@interface Project : NSObject
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id description:(NSString * _Nonnull)description OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10MorphiiSDK21ReactionCommentRecord")
@interface ReactionCommentRecord : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull text;
@property (nonatomic, readonly, copy) NSString * _Nonnull locale;
- (nonnull instancetype)initWithText:(NSString * _Nonnull)text locale:(NSString * _Nonnull)locale OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10MorphiiSDK13ReactionError")
@interface ReactionError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10MorphiiSDK27ReactionMorphiiResultRecord")
@interface ReactionMorphiiResultRecord : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull displayName;
@property (nonatomic, readonly) double intensity;
@property (nonatomic, readonly) NSInteger weight;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name displayName:(NSString * _Nonnull)displayName intensity:(double)intensity weight:(NSInteger)weight OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10MorphiiSDK20ReactionResultRecord")
@interface ReactionResultRecord : NSObject
@property (nonatomic, readonly) BOOL isSubmitted;
@property (nonatomic, readonly, copy) NSString * _Nullable reactionId;
@property (nonatomic, readonly, copy) NSString * _Nonnull viewId;
@property (nonatomic, readonly, copy) NSString * _Nonnull targetId;
@property (nonatomic, readonly, strong) ReactionCommentRecord * _Nullable comment;
@property (nonatomic, readonly, strong) ReactionMorphiiResultRecord * _Nullable morphii;
@property (nonatomic, strong) ReactionError * _Nullable error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10MorphiiSDK9Selection")
@interface Selection : NSObject
- (nonnull instancetype)initWithRequired:(BOOL)required OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10MorphiiSDK17SingleMorphiiView")
@interface SingleMorphiiView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDictionary;

SWIFT_CLASS("_TtC10MorphiiSDK6Target")
@interface Target : NSObject
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id type:(NSString * _Nonnull)type metadata:(NSDictionary * _Nullable)metadata OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface UIDevice (SWIFT_EXTENSION(MorphiiSDK))
@end


@interface UIImage (SWIFT_EXTENSION(MorphiiSDK))
@end


@interface UIView (SWIFT_EXTENSION(MorphiiSDK))
@end


SWIFT_CLASS("_TtC10MorphiiSDK4User")
@interface User : NSObject
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id type:(NSString * _Nonnull)type properties:(NSDictionary * _Nullable)properties OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

#pragma clang diagnostic pop
