# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MorphiiSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MorphiiSample
  pod 'MorphiiSDK', :git => 'https://github.com/Vizbii/morphii-sdk-ios.git', :tag => '0.0.65'
end
